"""Orchestrates requests between the UI and the Meta-Agent."""

from agent import MetaAgent


class Orchestrator:
    """Coordinates incoming user requests and delegates to agents."""

    def __init__(self):
        """Initialize the orchestrator and its agent dependencies."""
        print("Initializing Orchestrator...")
        self.meta_agent = MetaAgent()
        self.history = []  # Simple list for conversation history

    def handle_request(self, user_input):
        """Process user input and return the agent response.

        Args:
            user_input: The raw string from the user.

        Returns:
            str: Response generated by the Meta-Agent.
        """
        print(f"Orchestrator received: {user_input}")

        # Placeholder for future routing logic
        response = self.meta_agent.invoke(user_input, self.history)

        # Update history
        self.history.append({"user": user_input, "jarvis": response})
        return response
